# Generated by Django 5.1.3 on 2025-08-09 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_configuracaosite"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projeto",
            name="imagem",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="projetos/",
                verbose_name="Imagem do Projeto",
            ),
        ),
    ]
