# Generated by Django 5.1.3 on 2025-09-22 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_voluntario_aprovado_voluntario_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuracaosite",
            name="cidade",
            field=models.CharField(
                default="São Paulo", max_length=100, verbose_name="Cidade"
            ),
        ),
        migrations.AlterField(
            model_name="configuracaosite",
            name="qr_code_pix",
            field=models.ImageField(
                blank=True, null=True, upload_to="qr_codes/", verbose_name="QR Code PIX"
            ),
        ),
    ]
